apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rollbackpolicies.toolkit.fluxcd.io
spec:
  group: toolkit.fluxcd.io
  names:
    kind: RollbackPolicy
    plural: rollbackpolicies
    singular: rollbackpolicy
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targets:
                  type: array
                  items:
                    type: object
                    properties:
                      kind:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                debounceSeconds:
                  type: integer
                  default: 300
                gitlabProjectID:
                  type: integer
                gitlabTokenSecret:
                  type: string
                revertBranchPrefix:
                  type: string
                  default: revert
